### ISSUE TITLE
review

### ISSUE THREAD

**Issue by marianux** [openjournals/joss-papers#6]
General comments:
The toolkit submitted pursues a nice idea to share electrocardiogram (ECG) signal processing tools with the community through an open source toolbox. The main concern would be that there are several toolboxes that pursues the same goal. I think that the author would emphasize which are the differences with other existing approaches, or which advantages would this toolbox have.

WFDB project

https://github.com/MIT-LCP/wfdb-python

https://www.physionet.org/physiotools/wfdb.shtml

ECG-kit project
http://marianux.github.io/ecg-kit/

Documentation
Very short and poorly detailed. Lack of statement of need.

Installation instructions
Very poorly detailed.

Example usage
There is a demo.m example.

API documentation
Not acceptable.

Tests
Not present

Community guidelines

Contribute to the software
Acceptable, the contribution of new methods depends on the mantainer of the toolbox. Not properly documented for anyone who would like to collaborate with the project.

**Comment by hooman650** [comment]
@marianux 
Thank you very much for your comments and feedback.
Please see the update repository in regards to your comments on Documentation, Installation instructions and Example Usage and added CodeMap in the repository that makes it easier for the public contributors to join the project. Also, please note that each subroutine is extensively commented in order to make it easy to understand its functionality and use. 

Please see the comments below in regards to the other points:
-----

I agree with the reviewer that there are several other ECG processing tools already available that offer similar functionalities. However, please note that BioSigKit has several important differences:

1. It implements 5 popular algorithms that at least 3 of them (MTEO, Multi-scale Based and Phase Space QRS detector) are not implemented by the other toolboxes that the reviewer mentioned.

2. BioSigKit also implements all of its subroutines in native Matlab script. For instance, Pan-Tompkins algorithm which is a very popular QRS detector method among researchers is mostly implemented in C and most of the packages normally only create a wrapper in Matlab, while BioSigKit implements it in pure Matlab script, giving the opportunity to curious students and researchers to get a better understanding of its several stages. Therefore, BioSigKit was created with this goal in mind to not only be an analysis tool but also a platform to learn about how these algorithms are implemented and could be improved in the implementation manner.

3. BioSigKit is gathering many popular MatLab central submissions ([e.g. Pan-Tompkins Matlab which has been more than 13,000 times downloaded](https://www.mathworks.com/matlabcentral/fileexchange/45840-complete-pan-tompkins-implementation-ecg-qrs-detector),[Simple R, S and T wave detection](https://www.mathworks.com/matlabcentral/fileexchange/45404-ecg-q-r-s-wave-online-detector))  for signal processing and offering them under a unified and open source umbrella making it easier for the researchers to study them, use them or contribute to them.

4. The ultimate goal of BioSigKit is not to be only used for ECG processing, it aims to be helpful in analysis of several different physiological signals such as EMG, ACC and EDR as well. For instance the last subroutine which is a general peak detector can already be used in many different signals even with low frequencies (Please see [the paper by Scholkmann](http://www.mdpi.com/1999-4893/5/4/588). While its current version still does not offer more algorithms for processing of the other physiological signals, at least several more subroutines are in pipeline that will be able to do so in the near future. For instance,extracting Fetal ECG from maternal ECG using projection techniques, computing ECG derived respiration (EDR) or MUAP detection in EMG signals ([EMG toolbox (offered by the same author)](https://www.mathworks.com/matlabcentral/fileexchange/59344-toolbox-for-unsupervised-classification-of-muaps-and-action-potentials-in-emg)). 

5. BioSigKit does not claim to be the state of the art toolbox in ECG processing as validating each QRS detection method employed requires extensive analysis on MITDB or other benchmarks that would not suit the purpose of JOSS and make the paper specialized for a more biomedical engineering publication. However, the author has performed validations for the Pan-Tompkin's implementation that could be [found here
](https://www.researchgate.net/publication/313673153_Matlab_Implementation_of_Pan_Tompkins_ECG_QRS_detector). BioSigKit rather aims to be an easy to use platform for interested contributors in signal processing.

Best regards,
Hooman

**Comment by arfon** [comment]
Hi @marianux - I'm not sire which JOSS paper is the a review for? Regardless, please don't submit reviews to this repository - they should be on the review thread in the https://github.com/openjournals/joss-reviews repository. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
This was in relation to: https://github.com/openjournals/joss-reviews/issues/671#issuecomment-401154516
